import { create } from 'zustand';
import type { Task } from '@shared/types';
import type { SidebarView } from '@shared/types/settings';
import { useTaskStore, loadTasks } from './task-store';
import { useTerminalStore } from './terminal-store';
import { useProjectStore } from './project-store';

interface NavigationState {
  activeView: SidebarView;
  selectedTask: Task | null;
  isRefreshingTasks: boolean;

  setActiveView: (view: SidebarView) => void;
  setSelectedTask: (task: Task | null) => void;
  clearSelectedTask: () => void;
  setIsRefreshingTasks: (v: boolean) => void;
  goToTask: (taskId: string) => void;
  openInbuiltTerminal: (id: string, cwd: string) => void;
  refreshTasks: () => Promise<void>;
}

export const useNavigationStore = create<NavigationState>((set) => ({
  activeView: 'kanban',
  selectedTask: null,
  isRefreshingTasks: false,

  setActiveView: (view) => set({ activeView: view }),

  setSelectedTask: (task) => set({ selectedTask: task }),

  clearSelectedTask: () => set({ selectedTask: null }),

  setIsRefreshingTasks: (v) => set({ isRefreshingTasks: v }),

  goToTask: (taskId: string) => {
    set({ activeView: 'kanban' });
    const task = useTaskStore.getState().tasks.find(
      (t) => t.id === taskId || t.specId === taskId
    );
    if (task) {
      set({ selectedTask: task });
    }
  },

  openInbuiltTerminal: (_id: string, cwd: string) => {
    // Note: _id parameter is intentionally unused - terminal ID is auto-generated by addTerminal()
    // Parameter kept for callback signature consistency with callers
    console.debug('[Navigation] Opening inbuilt terminal:', { cwd });

    const { projects, activeProjectId, selectedProjectId } = useProjectStore.getState();
    const selectedProject = projects.find((p) => p.id === (activeProjectId || selectedProjectId));

    // Switch to terminals view and close modal
    set({ activeView: 'terminals', selectedTask: null });

    // Add terminal to store
    const terminal = useTerminalStore.getState().addTerminal(cwd, selectedProject?.path);

    if (!terminal) {
      console.error('[Navigation] Failed to add terminal to store (max terminals reached?)');
    } else {
      console.debug('[Navigation] Terminal added to store:', terminal.id);
    }
  },

  refreshTasks: async () => {
    const { activeProjectId, selectedProjectId } = useProjectStore.getState();
    const currentProjectId = activeProjectId || selectedProjectId;
    if (!currentProjectId) return;

    set({ isRefreshingTasks: true });
    try {
      await loadTasks(currentProjectId, { forceRefresh: true });
    } finally {
      set({ isRefreshingTasks: false });
    }
  },
}));
